name: wave_drive
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_flavorizr: ^2.4.1
  talker_flutter: ^5.0.1
  flutter_html: ^3.0.0
  talker_dio_logger: ^5.0.1
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  auto_route: ^10.1.2
  flutter_easyloading: ^3.0.5
  flutter_portal: ^1.1.4
  get_it: ^8.2.0
  path_provider: ^2.1.5
  dio: ^5.9.0
  qr_flutter: ^4.1.0
  retrofit: ^4.7.3
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  client_information: ^2.2.0
  flutter_secure_storage: ^9.2.4
  sentry: ^9.6.0
  path: ^1.9.1
  flutter_smart_dialog: ^4.9.8+9
  # objectbox: ^4.3.0
  package_info_plus: ^9.0.0
  timeago: ^3.7.1
  jiffy: ^6.4.3
  easy_localization: ^3.0.8
  share_plus: ^12.0.0
  bot_toast: ^4.1.3
  styled_text: ^8.1.0
  pull_to_refresh: ^2.0.0
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  flutter_svga: ^0.0.6
  gap: ^3.0.1
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  rocco_mobile_plugins:
    git:
      url: https://github.com/RoccoVideo/rocco-mobile-plugins-main.git
      ref: main
      path: rocco_mobile_plugins
  flutter_form_builder: ^10.2.0
  country_flags: ^4.0.1
  image_gallery_saver_plus: ^4.0.1
  auto_size_text: ^3.0.0
  animated_custom_dropdown: ^3.1.1
  lottie: ^3.3.2
  app_settings: ^6.1.1
  carousel_slider: ^5.1.1
  flutter_keyboard_visibility: ^6.0.0
  form_builder_validators: ^11.2.0
  freezed_annotation: ^3.1.0
  firebase_auth: ^6.1.1
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  web_socket_channel: ^3.0.3
  firebase_core: ^4.2.0
  url_launcher: ^6.3.2
  syncfusion_flutter_charts: ^31.2.3
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.5
  # objectbox_flutter_libs: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.3
  build_config: ^1.1.2
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  # objectbox_generator: ^4.3.0
  retrofit_generator: ^9.7.0
  uuid: ^4.5.1

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
    # - assets/icons/
    # - assets/fonts/
  # fonts:
  #   - family: Karla
  #     fonts:
  #       - asset: assets/fonts/Karla-Regular.ttf
  #       - asset: assets/fonts/Karla-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Karla-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Karla-SemiBold.ttf
  #         weight: 600


